### PR TITLE
warmup yuki

### PR DESCRIPTION
**Pull request by yagutaro**
I tried it again. How about this?

### CODE REVIEW

**Review by enkeboll — CHANGES_REQUESTED** [review]
I still want your gif to be added in the original `README.md` file, not a new `README-Yuki.md` file.  You can still do that in this branch-- just `git rm README-Yuki.md`, add your code to the original `README.md` file, commit, and push

**Comment by yagutaro** [comment]
I changed the original readme.md file this time but there is something I do not understand here. Let me check again.

**Comment by yagutaro** [comment]
Sorry, I just forgot to add and commit changes before pushing. I think it is reflected now. Do I have to open new pull request?

**Review by enkeboll — APPROVED** [review]
perfect!

**Pull request merged**
